export const FETCH_TVSHOWS = 'FETCH_TVSHOWS';
export const SET_SORTING_CRITERION = 'SET_SORTING_CRITERION';
export const FETCH_FAILURE = 'FETCH_FAILURE';
export const LOADING_STATE = 'LOADING_STATE';
