export const FETCH_TVSHOWS_REQUEST = 'FETCH_TVSHOWS_REQUEST';
export const FETCH_TVSHOWS_FAILURE = 'FETCH_TVSHOWS_FAILURE';
export const FETCH_TVSHOWS_SUCCESS = 'FETCH_TVSHOWS_SUCCESS';
export const SET_SORTING_CRITERION = 'SET_SORTING_CRITERION';
export const LOADING_STATE = 'LOADING_STATE';
